version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - RemindMeToDoDb-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=RemindMeToDoDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

volumes:
  RemindMeToDoDb-db-volume: