version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5434:5432 # Map port 5432 from the container to port 5434 on the host
    volumes:
      - RemindMeEmailingDb-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=RemindMeEmailingDb

volumes:
  RemindMeEmailingDb-db-volume: